### ISSUE TITLE
autoprefixer for grid in IE11?

### ISSUE THREAD

**Issue by jonasbjorkberg** [thysultan/stylis#119]
A year has gone by since this was last discussed, (https://github.com/thysultan/stylis.js/issues/51).
Since then Autoprefixer has implemented a decent support for css grid in IE11. See for example https://css-tricks.com/css-grid-in-ie-css-grid-and-the-new-autoprefixer/.
It would have been fantastic if stylis had the same support.

**Comment by izakfilmalter** [comment]
Ya this is causing a lot of headaches for my dev team atm.

**Comment by smeijer** [comment]
Would be awesome indeed. The fact that the IE grid is so different from any other implementation; prevents me from using it at all.

As long as IE is around, I stick to `Flex` *(which also has its share of issues (`-ms-flex-negative`))*.

Auto fixing grids would be **AWESOME**!

**Comment by fredconv** [comment]
Hi 

Any news about this one ? That would be **awesome**.
I'm looking forward to be able to use grid in all our components without any extra support for IE :) 

👍 

Thanks

**Comment by thysultan** [comment]
Open to review PR's on this if it doesn't bloat the bundle size a lot. Preferably on the `rewrite` branch where the prefixer is tree-shake-able.

**Comment by bzalasky** [comment]
@thysultan I'd like to take a crack at this if it's still open. We're using Emotion at Lookout, which depends on Stylis, and would like to adopt CSS Grid, but need to continue supporting IE 11 for the time being.

**Comment by thysultan** [comment]
@bzalasky Yes, feel free. Ping me if you have any questions.

**Comment by bzalasky** [comment]
Looking into it, it seems Emotion uses a Stylis fork that’s “been modified slightly to make it smaller.” Though it looks like all they’re doing is running it through Google Closure Compiler and Prettier, so it seems any changes here could potentially land there as well… though not sure how the rewrite branch fits into this then. Does the rewrite branch include breaking changes? Is it at parity with master?

**Comment by thysultan** [comment]
Yes the rewrite is major version bump so it might not make it into their release schedule. 

>Is it at parity with master?

It's not intended to maintain API parity with the current version.

**Comment by fredconv** [comment]
Just to know if there was any update on this part ? :) 

thanks

**Comment by JeroenReumkens** [comment]
@thysultan Could you point me in the right direction on how I could start adding this? I'd love to try to fix this, but at the moment don't have any idea where to start. I think this is a really important feature that is right now missing, since grid will is used more and more.

**Comment by TylerBarnes** [comment]
Since the article was originally linked at the start of this issue, autoprefixer has made further improvements to how they handle things. There's a new [piece](https://css-tricks.com/css-grid-in-ie-duplicate-area-names-now-supported/) added to that series if anyone's curious.

**Comment by thysultan** [comment]
@JeroenReumkens The bulk of vendor prefixing is handled by the `property` function in the current and `vendor` in rewrite. They both use partial-hashes to determine if a property/group of properties should be prefixed or not, the logic of that particular prefix follows into that. 

As i would imagine some grid properties might have properties and values that involve multiple arbitrary cross-cutting properties/values so it may get more involved in those specific cases(i.e grid-template-areas).

**Comment by nelsonomuto** [comment]
As a stop gap until this is resolved might be useful to create a wrapper that performs the prefixing...

**Comment by probablyup** [comment]
Maybe this could be a stylis plugin rather than built in? It is rather difficult to do the emulation properly and probably would be heavy enough to do properly that it shouldn't be part of core...

**Comment by grncdr** [comment]
> Maybe this could be a stylis plugin rather than built in? It is rather difficult to do the emulation properly and probably would be heavy enough to do properly that it shouldn't be part of core...

I've recently been trying to make some grid-based designs work in IE11 and so I took a stab at writing this as a plugin. Below is a (very incomplete) plugin that adds `-ms-grid` specific properties **in certain cases**.

There are giant caveats, some of which might be possible to overcome, but I don't know:

* Auto-placement is not (and probably never will be) functional. This means you still have to specify column & row numbers when  placing content in a grid. For my use case (react + emotion) this is not such a big deal, as I implement the placement logic in JS.
* IE11 does not support `grid-{row,column}-gap`. My current workaround is to add CSS rules like this (again, handling the logic in React components):
  ```css
  /* simulate `grid-gap: 15px` for IE <= 11 */
  @media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
    .grid-container > * {
       margin-right: 15px;
       margin-bottom: 15px;
    }

    .grid-container {
      margin-right: -15px;
      margin-bottom: -15px;
    }
  }
  ```
  Probably this could be integrated into the plugin, but I'm not convinced it works reliably enough to do it by default.

Anyways those caveats out of the way, here's the code:

```ts
import { Plugin } from '@emotion/stylis'

export function cssGridPrefixer(): Plugin {
  const gridPropRgx = /^grid-([a-z-]+): *(.+)/
  const repeatFnRgx = /repeat\((\d+), *(.+)\)/
  const isNumber = (v: string | undefined) => {
    const n = parseInt(v || '', 10)
    return !isNaN(n)
  }
  let selectorContext: {
    [key: string]: string | undefined
  } = {}

  const plugin: Plugin = function(
    stylisContext,
    content,
    selector,
    parent,
    line,
    column,
    length,
    at,
    depth,
  ) {
    switch (stylisContext) {
      case 2:
        selectorContext = {}
        break
      case 1:
        if (content === 'display:grid') {
          return `display:-ms-grid;display:grid`
        }
        const m = content.match(gridPropRgx)
        if (!m) {
          return
        }
        const [, name, value] = m
        switch (name) {
          case 'template-columns':
            const msValue = value.replace(repeatFnRgx, '($2)[$1]')
            return `-ms-grid-columns:${msValue};${content};`
          case 'row-start':
          case 'column-start':
            const axis = name.split('-')[0]
            selectorContext[name] = value
            return `-ms-grid-${axis}: ${value};\n${content};`
          case 'column-end':
            if (isNumber(selectorContext['column-start'])) {
              const columnStart = parseInt(selectorContext['column-start'] || '', 10)
              let columnEnd = parseInt(value.split(/\s+/).pop())
              if (value.startsWith('span')) {
                return `-ms-grid-column-span: ${columnEnd};\n${content};`
              } else {
                return `-ms-grid-column-span: ${columnEnd - columnStart};\n${content};`
              }
            }
          case 'column':
          case 'row':
            const [start, end] = value.split(/\s*\/\s*/)
            let output = plugin.call(
              this,
              stylisContext,
              `grid-${name}-start:${start}`,
              selector,
              parent,
              line,
              column,
              length,
              at,
              depth,
            )
            if (typeof end === 'string') {
              output +=
                ';' +
                plugin.call(
                  this,
                  stylisContext,
                  `grid-${name}-end:${end}`,
                  selector,
                  parent,
                  line,
                  column,
                  length,
                  at,
                  depth,
                )
            }
            return output
        }
    }
  }
  return plugin
}
```

**Comment by mjmonline** [comment]
This is of big importance, any updates?

**Comment by Emiliano-Bucci** [comment]
Any news on this?

**Comment by Nahov91** [comment]
Any updates on this?

**Comment by collegeimprovements** [comment]
Is there any workaround for this ?

**Comment by grncdr** [comment]
For all the people asking about updates: why not take the partially complete plugin I wrote above, modify as needed for your uses, and share the improvements?

**Comment by mjmonline** [comment]
@grncdr that's not really a good option. Also the `grid-template-area` approach is preferred because it works in [IE11 if autoprefixed](https://css-tricks.com/css-grid-in-ie-css-grid-and-the-new-autoprefixer/ ).

**Comment by probablyup** [comment]
@mjmonline sounds like you have some open source work to do then :)

**Comment by abumuawiyah** [comment]
for now, i am using https://autoprefixer.github.io/ to manually convert my styles.

**Comment by pjaws** [comment]
> for now, i am using https://autoprefixer.github.io/ to manually convert my styles.

@abumuawiyah You can use PostCSS to do this automatically as part of your build process.

**Comment by pjaws** [comment]
Is there an update on this? It's been over a year.

**Comment by Andarist** [comment]
And for over a year everybody had a chance to do something about it - its OSS, it is also your responsibility, not something that just happens out of thin air.

**Comment by probablyup** [comment]
Well said 👏🏼

**Comment by pjaws** [comment]
No, sorry, but it’s not my responsibility at all. I’m not the one who
created this package and promoted it. I’m just stuck using it, since I use
styled-components.

**Comment by probablyup** [comment]
Take your false sense of entitlement and shove it where the sun doesn’t
shine. All this stuff is volunteer work and unless you’re going to pay up
or help, shut up.

**Comment by pjaws** [comment]
Imagine creating an open source library and getting this angry when people
ask for updates on the most requested feature. 😂

**Comment by probablyup** [comment]
Reread your messages and assess if you’re being gracious about it since
you’re getting shit for free.

**Comment by pjaws** [comment]
I asked for an update on an obviously important feature that seemed like it
was going to be implemented a year ago. You guys immediately attacked me
and blamed me for not implementing it myself, when I didn't even know this
package existed until yesterday.

**Comment by stubbz** [comment]
This is vastly important to me and my team using styled-components, any updates?

**Comment by JawsomeJason** [comment]
@stubbz Good luck with that.  

> for now, i am using https://autoprefixer.github.io/ to manually convert my styles.

I recommend @abumuawiyah's approach if all else fails.

This issue might as well be closed by now.  Hell, after reading the snark by the contributors, I just use this site in my presentations as an example of, "Keep CSS Where It Belongs," because JS libraries will never stay up to date with features.  Gotta find the silver lining. 💅✨

**Comment by Andarist** [comment]
Maintainers here don't plan on working on this as it's just not that simple of a task and any attempts to autoprefix grid for IE11 have their edge cases. It's also a matter of "least surprise principle" - if we can't make it work for all cases, we don't want to make it at all because one could think they can use every grid-related feature safely when that would just not be true.

If you don't like our stance on this - you can attempt to write such a prefixer on your own, just like @grncdr did (👏). It should also be somewhat easier to write a custom prefixer plugin in the upcoming v4. Forking is really a viable option as well - you just can't demand maintainers to always do what you wish for and do it for free (or rather usually at the cost of their free time). I encourage you to read [this thread](https://twitter.com/brian_d_vaughn/status/1250121146961285121) - OSS maintainers are just humans and a demanding attitude from the community can only get them frustrated in the long run and less and less caring for projects.

**Comment by edxv** [comment]
Based on the great work of @grncdr above, I published a small plugin to add IE11 prefixes for some grid properties in Styled Components: [styled-griddie](https://github.com/edxv/styled-griddie).

Check out the readme to see what works so far — will look to add support for more grid features soon!

**Comment by Jojocaster** [comment]
Not quite an universal solution, but if anyone uses styled-system along with styled-components, I've got a workaround. 

Here's my `Col` component which I use as a grid-column:
```
export const Col = styled.div<SpaceProps & FlexboxProps & GridProps & DisplayProps>
  ${system({
    gridColumn: {
      //@ts-ignore - msGridColumn isn't part of CSS.Properties for some reason
      properties: ['gridColumn', 'msGridColumn'],
      scale: 'breakpoints',
      transform: value => `${value}`,
    },
    gridRow: {
      //@ts-ignore - msGridRow isn't part of CSS.Properties for some reason
      properties: ['gridRow', 'msGridRow'],
      scale: 'breakpoints',
      transform: value => `${value}`,
    },
  })}
```

This will add the prefixes for our beloved IE11. Obviously this is a fairly simple example, and there's only so much we can do with prefixes. But with "simple" grids, that'll do the trick (and I'm sure we can do more with the `transform` attribute).

PS: I'm using a set of breakpoints as a scale so I can pass an object to my component, and handle columns via media queries.

**Comment by SukkaW** [comment]
@Andarist @thysultan 
I decide to work on this issue. Would you mind reopening it for further discussion?
