### ISSUE TITLE
Support "inset" property

### ISSUE THREAD

**Issue by tigrr** [thysultan/stylis#268]
The `inset` CSS property is a shorthand that corresponds to the `top`, `right`, `bottom`, and/or `left` properties.
Unfortunately, it is not supported in older Safari browsers - both desktop and mobile.
Please, add cross-browser support with a polyfill for this property if possible.

**Comment by thysultan** [comment]
Yes, it's possible. I'll look into it.

**Comment by awinogrodzki** [comment]
Hey @thysultan!

Any updates on this one?
