### ISSUE TITLE
`@supports not` is not supported

### ISSUE THREAD

**Issue by grabbou** [thysultan/stylis#308]
Hey,

Playing around with Styled Components I've noticed that while `@supports` syntax is supported, `@supports not` is not. For example, `@supports not (container-type: inline-size)` will not have any effect.

**Comment by Andarist** [comment]
Could you share a repro case? The current major version of Styled-Components (v5) is using the old version of Stylis (v3). However, I've tested it with [that old version](https://unpkg.com/browse/stylis@3.5.4/stylis.min.js) and it seems to work:
```ts
const res = stylis('.user', `

@supports not (container-type: inline-size) {
  display: block;
}

`)

res // '@supports not (container-type:inline-size){.user{display:block;}}'
```

The more recent version of Stylis (v4) can be tested on [our homepage](https://stylis.js.org/) and as far as I could test this particular example it also seems to work fine with it.
