### ISSUE TITLE
Namespace omitted for comma-joined selectors in some scenarios

### ISSUE THREAD

**Issue by quantizor** [thysultan/stylis#321]
![Screenshot 2023-12-22 at 9 00 18 AM](https://github.com/styled-components/styled-components/assets/570070/b7b22343-ede8-4145-8ade-1550f39ea232)

Given the following:

```
div {
  display: flex;

  &.foo,
  p:not(:last-child) {
    background: red;
  }
}
```

The output is currently:

```
[namespace] div {
	display: -webkit-box;
	display: -webkit-flex;
	display: -ms-flexbox;
	display: flex;
}

[namespace] div.foo,p:not(:last-child) {
	background: red;
}
```

But it should be:

```
[namespace] div {
	display: -webkit-box;
	display: -webkit-flex;
	display: -ms-flexbox;
	display: flex;
}

[namespace] div.foo,[namespace] p:not(:last-child) {
	background: red;
}
```

Note the lack of `[namespace]` for the second selector in the comma chain.

**Comment by Andarist** [comment]
This is a regression from: https://github.com/thysultan/stylis/commit/ccb001641bead49b660344956252d1a0dd4d38f1

**Comment by quantizor** [comment]
I think the bug is at least as old as 4.x just based on testing with this example repo https://github.com/arackaf/styled-components-repro (I'm using package.json `overrides` to force particular versions.)
