### ISSUE TITLE
Support logical property

### ISSUE THREAD

**Issue by Heet-Bhalodiya** [thysultan/stylis#331]
The `inset` CSS property is a shorthand for the `top`, `right`, `bottom`, and `left` properties. However, it is not supported in `stylis`, causing issues in our project. Could you let me know if there will be support for this in the future and provide a timeline for it?

Another question I have is whether it is possible to exclude certain lines of code from RTL conversion. For example, if I want to exclude a specific block from RTL, can I use comments or some other method to make Stylis ignore that block?

**Comment by Andarist** [comment]
> The inset CSS property is a shorthand for the top, right, bottom, and left properties. However, it is not supported in stylis, causing issues in our project.

It's not apparent what the issue u are facing is. Please always provide a repro case.

> Could you let me know if there will be support for this in the future and provide a timeline for it?

There is no timeline for the unpaid work that is done on this project. If you are facing issues that are important for your project then you can sponsor that work (given that it's something that aligns with the project's maintainers vision for the project).

> Another question I have is whether it is possible to exclude certain lines of code from RTL conversion. For example, if I want to exclude a specific block from RTL, can I use comments or some other method to make Stylis ignore that block?

RTL conversions are done through plugins. This is not the core of Stylis project. You should raise it with the maintainers of the plugin that you are using.
