### ISSUE TITLE
property 'backdrop-filter' is not vendor prefixed

### ISSUE THREAD

**Issue by ivansheshin** [thysultan/stylis#332]
I'm using last version of stylis and property backdrop-filter is not prefixed
this is relevant for safari which supports only prefixed version of the property

**Comment by thysultan** [comment]
See the test(it is being prefixed): https://github.com/thysultan/stylis/commit/8c9f0cae6999db3dcf172392a73165ccdceb45c7#diff-0a11d7a41a1604b45d7a01be129e3d3ad431b1b167d1dcbbddd51e262b464bfeR180-R183
